---

- name: Install NGINX
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Deploy main configuration
  notify: restart nginx
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
    validate: nginx -T -c %s

- name: Configure NGINX proxying
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true