---

- name: update_password | Update user account password
  ansible.builtin.user:
    name: "{{ user_name }}"
    state: present
    password: "{{ user_password | password_hash('sha512') }}"
    update_password: always
