---

- name: AAP Controller Configuration
  hosts: controller
  gather_facts: false
  become: false

  vars_prompt:
    - name: manifest_path
      prompt: Path to manifest file
      default: "~/.ansible/manifest.zip"

  module_defaults:
    group/awx.awx.controller:
        controller_host: "https://{{ ansible_host }}"
        controller_username: admin
        controller_password: "{{ admin_password | default('admin') }}"
        validate_certs: false

  tasks:
    - name: Upload manifest to Automation Controller
      delegate_to: localhost
      when: inventory_hostname == groups['controller'][0] 
      awx.awx.license:
        manifest: "{{ lookup('pipe', 'readlink -f '+ manifest_path) }}"
        state: present
        force: true

    - name: Configure project to use demonpig/aap-example-project
      delegate_to: localhost
      awx.awx.project:
        name: Example Project
        organization: Default
        state: present
        scm_url: https://github.com/demonpig/aap-example-project
        scm_type: git
        scm_clean: true
        state: present
        update_project: true

    - name: Create common job templates used for debugging
      delegate_to: localhost
      loop:
        - name: Long
          playbook: playbooks/long.yml
        - name: Ping
          playbook: playbooks/ping.yml
      awx.awx.job_template:
        name: "{{ item.name }}"
        job_type: run
        organization: Default
        inventory: Demo Inventory
        project: Example Project
        playbook: "{{ item.playbook }}"
        state: present