---

- name: Setup Docker
  hosts: all
  gather_facts: true

  tasks:
    - name: Install docker repository
      block:
        - name: Download repofile
          ansible.builtin.get_url:
            url: https://download.docker.com/linux/centos/docker-ce.repo
            dest: /etc/yum.repos.d/docker-ce.repo
            owner: root
            group: root
            mode: '0644'

      # there may be more steps for this block but leaving this for right now

    - name: Install docker components
      ansible.builtin.dnf:
        name:
          - containerd.io
          - docker-buildx-plugin
          - docker-ce
          - docker-ce-cli
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Start the docker service
      ansible.builtin.systemd:
        name: docker.service
        state: started

    - name: Add users to the docker group
      loop: "{{ users_accounts }}"
      ansible.builtin.user:
        user: "{{ item.name }}"
        append: true
        groups:
          - docker
